#!/usr/bin/env python3
import rospy
from colorama import Back, Style, Fore
from p_g3_driver.msg import chat


class Chatter:
    def __init__(self):
        red_players = rospy.get_param('/red_players')
        green_players = rospy.get_param('/green_players')
        blue_players = rospy.get_param('/blue_players')
        allplayers = [*red_players, *green_players, *blue_players]
        for player in allplayers:
            rospy.Subscriber('/' + player + '/chatter', chat, self.stateCallback)

    def stateCallback(self, chat):
        if 'red1' in chat.player or 'red2' in chat.player or 'red3' in chat.player:
            print(Fore.RED + chat.player + ' ' + Style.RESET_ALL + chat.status)
        elif 'green1' in chat.player or 'green2' in chat.player or 'green3' in chat.player:
            print(Fore.GREEN + chat.player + ' ' + Style.RESET_ALL + chat.status)
        elif 'blue1' in chat.player or 'blue2' in chat.player or 'blue3' in chat.player:
            print(Fore.BLUE + chat.player + ' ' + Style.RESET_ALL + chat.status)


def main():
    rospy.init_node('p_g3_chatter', anonymous=False)
    p_g3_chatter = Chatter()
    rospy.spin()


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInterruptException:
        pass
