#!/usr/bin/env python3
import numpy as np

# ---------------------------------------------------
#   Parameters
# ---------------------------------------------------

# Masks - Color ranges
# TODO Verificar valores
# Red color
lower_red = np.array([0, 0, 90])
upper_red = np.array([40, 40, 256])

# Green color
lower_green = np.array([0, 90, 0])
upper_green = np.array([40, 256, 40])

# Blue color
lower_blue = np.array([90, 0, 0])
upper_blue = np.array([256, 40, 40])
